### ISSUE TITLE
Update for 4.26?

### ISSUE THREAD

**Issue by DarthSoul92** [sigtrapgames/VrTunnellingPro-UE4#3]
Hi!
I've tried to compile the plugin to 4.26 version but it doesn't work. Any chances you may update the source? 
Also, awesome work and thank you for making it free :)

**Comment by darbycostello** [comment]
Sorting it as we speak.

**Comment by darbycostello** [comment]
There we go friend. Still awaiting Epic to green light the 4.26 update on the Marketplace, but available here from source. Thanks for your patience.

**Comment by DarthSoul92** [comment]
Thanks a lot!
