### ISSUE TITLE
Can't get color vignette to work UE4.26

### ISSUE THREAD

**Issue by wisien92** [sigtrapgames/VrTunnellingPro-UE4#4]
Hi,

I am trying to use this plugin in our project but I cannot get it to display any color vignette tunneling.

I have looked at example project - I added execute command from blueprint, I have added VRTP Mobile component to player and I use force option to test out but nothing happens.

Is there something I am missing (I must add it's mobie android project targetting oculus quest 1 and 2).

**Comment by darbycostello** [comment]
Hi. I could use a little more info about how you have set up your project. 

1. Are you using forward rendering?
2. Are you using instanced stereo?
3. Did the example project compile directly to your Quest or have you simply tried to use the components from the plugin in a fresh mobile project?
4. Do any of the modes from the example project work on your Quest?

**Comment by wisien92** [comment]
Sure:

1) both options from ForwardRendering section of settings are enabled
2) instanced stereo is disabled
3) I havent compiled yet - I am testing in editor
4) nope

In exanoke orihect I have also changed target hardware to mobile and graphical settings to scaleable 2d/3d and the effect stopped working - so maybe that's a clue?

**Comment by darbycostello** [comment]
Okay I'll try and replicate at this end. We developed this plugin against Quest in the first instance, but some settings may have changed in the past few years since it was tested.

**Comment by wisien92** [comment]
Ok I have moved PostProcess effects and it seems to be working.
