### ISSUE TITLE
Any UE5 roadmap?

### ISSUE THREAD

**Issue by dav01d** [sigtrapgames/VrTunnellingPro-UE4#5]

**Comment by darbycostello** [comment]
Hi. No roadmap per se, but given the functional similarities between 4.27 and what’s available in the UE5 preview, it should be fairly straightforward to update. I guess we’ll be in a better position to address this once UE5 gets closer to a stable release.

**Comment by dav01d** [comment]
Thanks for the reply! Any chance for Mobile/Quest 2 support in the future?
